# Generated by Django 3.1.4 on 2022-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Unique title for each category of post', max_length=50, unique=True, verbose_name='Title')),
            ],
        ),
    ]
