# Generated by Django 3.1.4 on 2022-03-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220307_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(null=True, upload_to='posts/', verbose_name='Post Banner Image'),
        ),
    ]
