# Generated by Django 3.1.4 on 2022-03-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=True, help_text='Will this post be published?', verbose_name='Publish'),
        ),
    ]
